#端口配置
server:
  port: 8080

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: root
  #模板引擎
  freemarker:
    #关闭缓存
    cache: false
    request-context-attribute: request
    #引擎加载位置
    template-loader-path: classpath:/templates
    suffix: .htm
    prefix: /htm/
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      #静态资源文件
  resources:
    static-locations: /WEB-INF/resources/
#mybatis配置
mybatis:
  #实体类所在位置
  type-aliases-package: com.yjj.sys_demo.sys.model
  #mapper.xml所在位置
  mapper-locations: classpath:/mapper/*.xml